# Generated by Django 2.2.6 on 2020-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_chamado_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
