# Generated by Django 2.2.6 on 2020-01-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_chamado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='data_inicio',
        ),
    ]
