# Generated by Django 2.2.6 on 2020-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_remove_chamado_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_inicio',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
